Python/web_tool/flask/app/tool/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, TextAreaField, SelectField
from wtforms.validators import DataRequired, URL, ValidationError
from app.auth.users import User
from app.tool.service import data_type_list
import json
#import inspect

class InputStrForm(FlaskForm):
    input_str = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Del')

class PostDataForm(FlaskForm):
    data_type = SelectField('Data Type', choices=data_type_list)
    input_json = TextAreaField('Data', validators=[DataRequired()])
    addr = StringField('addr', validators=[DataRequired(), URL()])
    submit = SubmitField('Post Data')

class GetDataForm(FlaskForm):
    data_type = SelectField('Data Type', choices=data_type_list)
    addr = StringField('addr', validators=[DataRequired(), URL()])
    submit = SubmitField('Submit')

class InputNumForm(FlaskForm):
    input_num = IntegerField('Code', validators=[DataRequired()])
    submit = SubmitField('Send')

class InputDataForm(FlaskForm):
    name = StringField('name', validators=[DataRequired()])
    input_data = TextAreaField('data', validators=[DataRequired()])
    data_type = SelectField('Data Type', choices=data_type_list)
    submit = SubmitField('OK')

    def validate_input_data(self, username):
        print('xxxxx' + self.data_type.data)
        if self.data_type.data == data_type_list[1][0]:
            try:
                json.loads(self.input_data)
            except json.JSONDecodeError:
                raise ValidationError('Invalid data format.')

Python/web_tool/flask/app/tool/__init__.py
from flask import Blueprint

bp = Blueprint('tool', __name__)

from app.tool import routes

Python/web_tool/flask/app/tool/routes.py
from app import db, socketio
from flask import render_template, flash, redirect, url_for, abort
from app.tool.forms import PostDataForm, InputNumForm, GetDataForm, InputDataForm, InputStrForm
from flask_login import current_user, login_user, logout_user, login_required
from app.auth.users import User
from flask import request as flask_request
from werkzeug.urls import url_parse
from urllib import request, parse, error
from app.tool import bp
from app.errors.handlers import err_code_list
from app.tool.service import Service, data_type_list
from flask_socketio import send, emit

from threading import Lock
import json
import time

thread = None
thread_lock = Lock()

@bp.route('/service', methods=['GET', 'POST'])
def tool_service():
    form = InputDataForm()
    if form.validate_on_submit():
        service = Service()
        service.name = form.name.data
        service.data_type = form.data_type.data
        service.data = form.input_data.data
        db.session.add(service)
        db.session.commit()
        flash(form.name.data + ' Save success!')
    return render_template('tool/service.html', title='Tool', form=form)

@bp.route('/service_list', methods=['GET', 'POST'])
def tool_service_list():
    form = InputStrForm()
    services = Service.query.all()
    if form.validate_on_submit():
        service = Service.query.filter_by(name=form.input_str.data).first_or_404()
        
        db.session.delete(service)
        db.session.commit()
        services = Service.query.all()
        flash(form.input_str.data + ' Del success!')
    return render_template('tool/service_list.html', title='Tool', form=form, services=services)

@bp.route('/service/<name>')
def tool_service_one(name):
    service = Service.query.filter_by(name=name).first_or_404()
    if service.data_type == data_type_list[1][0]:
        return json.loads(service.data)
    else:
        return service.data

@bp.route('/post_data', methods=['GET', 'POST'])
def tool_post_data():
    form_post = PostDataForm()
    response = ''
    if form_post.validate_on_submit():
        post_data = json.dumps(form_post.input_json.data)
        post_addr = form_post.addr.data
        post_type = form_post.data_type.data
        if post_type == data_type_list[1][0]:
            headers = {
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            }
            data = json.loads(post_data)
        else:
            headers = ''
            data = post_data
        req = request.Request(post_addr, '', headers)
        try:
            f = request.urlopen(req, data=data.encode('utf-8'))
            response = f.read().decode('utf-8')
        except error.HTTPError as e:
            response = post_addr + str(e)
    return render_template('tool/post_data.html', title='Tool', form_post=form_post, response=response)

@bp.route('/get_data', methods=['GET', 'POST'])
def tool_get_data():
    form_get = GetDataForm()
    response = ''
    if form_get.validate_on_submit():
        post_addr = form_get.addr.data
        req = request.Request(post_addr)
        try:
            f = request.urlopen(req)
            if form_get.data_type == data_type_list[1][0]:
                res_data = json.loads(f.read())
                response = json.dumps(res_data,sort_keys=True, indent=4)
            else:
                response = f.read()
        except error.HTTPError as e:
            response = post_addr + str(e)
    return render_template('tool/get_data.html', title='Tool', form_get=form_get, response=response)

@bp.route('/export_err', methods=['GET', 'POST'])
def tool_export_err():
    form = InputNumForm()
    if form.validate_on_submit():
        err_code = form.input_num.data
        code_list = []
        for code in err_code_list:
            code_list.append(code['code'])
        if err_code in code_list:
            abort(err_code)
        else:
            flash('Invalid error code.', err_code)
    return render_template('tool/export_err.html', title='Export ERR', form_err=form)


@bp.route('/export_err/<err_code>')
def tool_export_err_code(err_code):
    code_list = []
    err_code = int(err_code)
    for code in err_code_list:
        code_list.append(code['code'])
    if err_code in code_list:
        abort(err_code)
    else:
        abort(404)



@bp.route('/long_connect')
def tool_long_connect():
   return render_template('tool/long_connect.html', title='Long Connection')

def background_thread():
    count = 0
    while True:
        count += 1
        t = time.strftime('%M:%S', time.localtime())
        socketio.emit('server_msg', {'data': t, 'count': count}, namespace='/tool_io')
        socketio.sleep(1)

@socketio.on('connect', namespace='/tool_io')
def tool_connect():
    print('Client connected')
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(target=background_thread)
    emit("server_log", {'data':'Connect'})

@socketio.on('disconnect', namespace='/tool_io')
def tool_disconnect():
    print('Client disconnected')

@socketio.on('recv_msg', namespace='/tool_io')
def tool_recv_msg(message):
    print("message:" + message['data'])
    emit("server_log", {'data': message['data']})

Python/web_tool/flask/app/templates/tool/export_err.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %} 
    <h2>Export Error</h2>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form_err) }}
        </div>
    </div>
{% endblock %}

Python/web_tool/flask/app/templates/tool/get_data.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %} 
    <h2>Get Data</h2>
    <div class="row">
        <div class="col-md-4" >
            {{ wtf.quick_form(form_get) }}
            <br>
            Response:<br>
            <div style="white-space: pre-line">{{ response }}</div>
        </div>
    </div>
{% endblock %}

Python/web_tool/flask/app/templates/tool/long_connect.html
{% extends "base.html" %}

{% block app_content %} 
<h2>Long Connection</h2>
<script src="//code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
    <div class="row">
        <div class="col-md-4">
            <script type="text/javascript">
                $(document).ready(function() {
                    namespace = '/tool_io';
                    var socket = io(namespace);
                    socket.on('connect', function() {
                        socket.emit('recv_msg', {data: 'I\'m connected!'});
                    });
                    socket.on('server_log', function(msg, cb) {
                        $('#log').append('<br>' + $('<div/>').text('Received: ' + msg.data).html());
                        //$('#log').append(''.text('Received: ' + msg.data));
                        if (cb)
                            cb();
                    });

                    socket.on('server_msg', function(msg) {
                        $('#msg').text('Time: ' + msg.data);
                    });
            
                });
                
            </script>
            <h2 id="msg"></h2>
            <div id="log"></div>
        </div>
    </div>
{% endblock %}

Python/web_tool/flask/app/templates/tool/post_data.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %} 
    <h2>Post Data</h2>
    <div class="row">
        <div class="col-md-4" >
            {{ wtf.quick_form(form_post) }}
            <br>
            Response:<br>
            <div style="white-space: pre-line">{{ response }}</div>
        </div>
    </div>
{% endblock %}

Python/web_tool/flask/app/templates/tool/service.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %} 
    <h2>Post Json</h2>
    <div class="row">
        <div class="col-md-4" >
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

Python/web_tool/flask/app/templates/tool/service_list.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %} 
    <h2>Service List</h2>
    <div class="row">
        <div class="col-md-4" >
            {% for service in services %}
            <li><a href="{{ url_for('tool.tool_service_one', name=service) }}" id=test>{{ service }}</a>
            {% endfor %}
            <br>
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

Python/web_tool/flask/app/templates/tool/tool.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %} 
    <a href="{{ url_for('tool.tool_service') }}">Service</a>
    <br>
    <a href="{{ url_for('tool.tool_service_list') }}">Service list</a>
    <br>
    <a href="{{ url_for('tool.tool_get_data') }}">Get data</a>
    <br>
    <a href="{{ url_for('tool.tool_post_data') }}">Post data</a>
    <br>
    <a href="{{ url_for('tool.tool_long_connect') }}">Long connection</a>
    <br>
    <a href="{{ url_for('tool.tool_export_err') }}">Export error</a>
    <br>
{% endblock %}